title: Hasan's Blog # name of the site
author: MD Ahad Hasan # name of site's author
email: hasan.rafi@icloud.com # email of site's author
url: https://joker666.github.io # root address of the site
tagline: Personal site with blogs in software engineering and devops
description: > # description of the site (multiple lines allowed)
  Personal site where you get my social and work information. I also write about golang,
  software engineering, devops stuff
twitter:
  username: hasantalks
  card: summary

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM